name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: Run ruff
        run: ruff check app/
      
      - name: Run mypy
        run: mypy app/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman fuse-overlayfs slirp4netns
      
      - name: Configure podman rootless
        run: |
          mkdir -p ~/.config/containers
          echo "safeai:100000:65536" | sudo tee /etc/subuid
          echo "safeai:100000:65536" | sudo tee /etc/subgid
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: Run tests
        run: pytest --cov=app --cov-report=xml --cov-report=term
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: Check for unsigned manifests in repo
        run: |
          if git diff origin/main --name-only | grep -E '\.(py|yaml|json)$'; then
            echo "Policy check: Source changes detected"
            # In production, verify all changes are signed
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t safe-ai-governor:latest .
      
      - name: Test Docker image
        run: |
          docker run --rm safe-ai-governor:latest python -c "import app; print('OK')"
